/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.masterdata.penjual.barangbesar.view;
import Sinarelektronikapp.config.UserLevel;
import Sinarelektronikapp.masterdata.penjual.barangbesar.controller.tipeController;
import Sinarelektronikapp.masterdata.penjual.barangbesar.database.tipeDatabase;
import Sinarelektronikapp.masterdata.penjual.barangbesar.entity.tipe;
import Sinarelektronikapp.masterdata.penjual.barangbesar.error.TipeException;
import Sinarelektronikapp.masterdata.penjual.barangbesar.model.event.tipeListener;
import Sinarelektronikapp.masterdata.penjual.barangbesar.model.tabelModelTipe;
import Sinarelektronikapp.masterdata.penjual.barangbesar.model.tipeModel;
import Sinarelektronikapp.masterdata.penjual.barangbesar.service.tipeDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author FAUZI
 */
public class JIFPenjualBarangBesarView extends javax.swing.JInternalFrame implements tipeListener, ListSelectionListener{

    /**
     * Creates new form JIFPenjualBBView
     */
    private tipeController controller;
    
    private tabelModelTipe tabelmodelTipe;
    
    private tipeModel model;
    
    public JIFPenjualBarangBesarView() {
        try {
            tabelmodelTipe = new tabelModelTipe();
            
            model = new tipeModel();
            model.setListener(this);
            
            controller = new tipeController(model);
            
            initComponents();
            
            tabelTipe.getSelectionModel().addListSelectionListener(this);
            tabelTipe.setModel(tabelmodelTipe);

            loadId();
            txtTipe.requestFocus();
            LoadDatabase();        
        } catch (SQLException ex) {
            Logger.getLogger(JIFPenjualBarangBesarView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TipeException ex) {
            Logger.getLogger(JIFPenjualBarangBesarView.class.getName()).log(Level.SEVERE, null, ex);
        }
        setLevel();
    }


    public void setLevel(){
        UserLevel userLevel = new UserLevel();
        String levelAktif = userLevel.getUserLevelActive();
        switch(levelAktif){
            case "Pemilik Toko":
                    txtTipe.setEnabled(true);
                    btSimpan.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Administrator":
                    txtTipe.setEnabled(true);
                    btSimpan.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Karyawan":
                    txtTipe.setEnabled(false);
                    btSimpan.setEnabled(false);
                    btDelete.setEnabled(false);
                    btReset.setEnabled(false);
                    btUpdate.setEnabled(false);                
                break;                        
            default:;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTipe = new javax.swing.JTable();
        bawah = new javax.swing.JPanel();
        btSimpan = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        palingAtas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtTipe = new javax.swing.JTextField();
        txtPersentaseInsentif = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Manajemen Penjual Barang Besar");
        setPreferredSize(new java.awt.Dimension(400, 300));

        atas.setLayout(new java.awt.BorderLayout());

        tabelTipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTipe);

        atas.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(atas, java.awt.BorderLayout.CENTER);

        bawah.setLayout(new java.awt.GridLayout(1, 4));

        btSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/tambah.png"))); // NOI18N
        btSimpan.setMnemonic('T');
        btSimpan.setFocusable(false);
        btSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        bawah.add(btSimpan);

        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/update2.png"))); // NOI18N
        btUpdate.setMnemonic('U');
        btUpdate.setFocusable(false);
        btUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        bawah.add(btUpdate);

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/hapus.png"))); // NOI18N
        btDelete.setMnemonic('H');
        btDelete.setFocusable(false);
        btDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        bawah.add(btDelete);

        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/reset.png"))); // NOI18N
        btReset.setMnemonic('R');
        btReset.setFocusable(false);
        btReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        bawah.add(btReset);

        getContentPane().add(bawah, java.awt.BorderLayout.PAGE_END);

        palingAtas.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        jLabel2.setText("Id :");
        jPanel1.add(jLabel2);

        jLabel1.setText("Nama :");
        jPanel1.add(jLabel1);

        jLabel3.setText("Persentase Insentif :");
        jPanel1.add(jLabel3);

        palingAtas.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.GridLayout(3, 0));

        txtId.setEditable(false);
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFocusGained(evt);
            }
        });
        jPanel2.add(txtId);

        txtTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipeActionPerformed(evt);
            }
        });
        jPanel2.add(txtTipe);

        txtPersentaseInsentif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersentaseInsentifActionPerformed(evt);
            }
        });
        jPanel2.add(txtPersentaseInsentif);

        palingAtas.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(palingAtas, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadId() throws SQLException, TipeException{
        txtId.setText(String.valueOf(getLastId()));
        txtTipe.setText("");
        txtTipe.requestFocus();
    }
    
    public int getLastId() throws SQLException, TipeException{
        tipeDao dao=tipeDatabase.getTipeDao();
        return dao.getLastIdata()+1;
    }
    
    public JTextField getTxtTipe() {
        return txtTipe;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTable getTabelTipe() {
        return tabelTipe;
    }

    public JTextField getTxtPersentaseInsentif() {
        return txtPersentaseInsentif;
    }

    public void setTxtPersentaseInsentif(JTextField txtPersentaseInsentif) {
        this.txtPersentaseInsentif = txtPersentaseInsentif;
    }
    
    private void delete(){
        controller.deleteTipe(this);
        controller.resetTipe(this);
        try {
            loadId();
        } catch (SQLException ex) {
            Logger.getLogger(JIFPenjualBarangBesarView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TipeException ex) {
            Logger.getLogger(JIFPenjualBarangBesarView.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTipe.setText("");
        txtPersentaseInsentif.setText("");
    }    
    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_btSimpanActionPerformed

    private void update(){
        controller.updateTipe(this);
        try {
            loadId();
        } catch (SQLException ex) {
            Logger.getLogger(JIFPenjualBarangBesarView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TipeException ex) {
            Logger.getLogger(JIFPenjualBarangBesarView.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTipe.setText("");
        txtPersentaseInsentif.setText("");
        txtTipe.requestFocus();        
    }                
    
    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        controller.resetTipe(this);
    }//GEN-LAST:event_btResetActionPerformed

    private void txtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusGained

    }//GEN-LAST:event_txtIdFocusGained

    public void tambah(){
        controller.insertTipe(this);
        try {
            loadId();
        } catch (SQLException ex) {
            Logger.getLogger(JIFPenjualBarangBesarView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TipeException ex) {
            Logger.getLogger(JIFPenjualBarangBesarView.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTipe.setText("");
        txtPersentaseInsentif.setText("");
        txtTipe.requestFocus();                
    }
    
    private void txtTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipeActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_txtTipeActionPerformed

    private void txtPersentaseInsentifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersentaseInsentifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersentaseInsentifActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel palingAtas;
    private javax.swing.JTable tabelTipe;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPersentaseInsentif;
    private javax.swing.JTextField txtTipe;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(tipeModel model) {
        txtId.setText(model.getIdtipe());
        txtTipe.setText(model.getNamaTipe());
        txtPersentaseInsentif.setText(String.valueOf(model.getInsentif()));
    }

    @Override
    public void onInsert(tipe tipe) {
        tabelmodelTipe.add(tipe);
    }

    @Override
    public void onUpdate(tipe tipe) {
        int index = tabelTipe.getSelectedRow();
        tabelmodelTipe.set(index, tipe);
    }

    @Override
    public void onDelete() {
        int index = tabelTipe.getSelectedRow();
        tabelmodelTipe.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            tipe model = tabelmodelTipe.get(tabelTipe.getSelectedRow());
            txtId.setText(model.getIdtipe());
            txtTipe.setText(model.getNamaTipe());
            txtPersentaseInsentif.setText(String.valueOf(model.getInsentif()));
        } catch (IndexOutOfBoundsException exception) {
            //JOptionPane.showMessageDialog(null, "Error pada overriding value Changed dengan pesan "+e);
        }
    }
    
    public void LoadDatabase() throws SQLException, SQLException, TipeException {
        tipeDao  dao = tipeDatabase.getTipeDao();
        tabelmodelTipe.setList(dao.selectAllTipe());
    }    
}
