/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.maintenance;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Fauzi
 */
public class maintenanceView extends javax.swing.JPanel {

    /**
     * Creates new form maintenanceView
     */
    public maintenanceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        btCari = new javax.swing.JButton();
        btExport = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(390, 90));

        jLabel1.setText("Pilih Lokasi :");

        btCari.setText("Cari");
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });

        btExport.setText("Export");
        btExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCari))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btExport))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExport))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExportActionPerformed
        // TODO add your handling code here:
        String lokasiDir = txtLokasi.getText();
        if(lokasiDir.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Lokasi untuk back up database masih belum ditentukan", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            String newLokasiDir = lokasiDir.replace('\\', '/');
            Date d = new Date();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd_MM_yyyy");
            String tanggal = dateFormat.format(d);
            String cmd = "c:/xampp/mysql/bin/mysqldump.exe --user=root --password=  sinarelektronik --result-file="+newLokasiDir+"Backup_SinarElektronik_tanggal_"+tanggal+".sql";
            Process p = null;        
            try{
                Runtime runtime = Runtime.getRuntime();
                p = runtime.exec(cmd);
                JOptionPane.showMessageDialog(null, "Back up database berhasil","Informasi", JOptionPane.INFORMATION_MESSAGE);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error export database karena "+e);
            }finally{
                if(p!=null){
                    p.destroy();
                }                
            }
        }
    }//GEN-LAST:event_btExportActionPerformed

    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
        // TODO add your handling code here:
        JFileChooser pick = new JFileChooser();
        pick.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int oke = pick.showOpenDialog(null);
        if(oke == JFileChooser.APPROVE_OPTION){
            String path = pick.getSelectedFile().getPath();
            txtLokasi.setText(path);
        }else{

        }
    }//GEN-LAST:event_btCariActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCari;
    private javax.swing.JButton btExport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtLokasi;
    // End of variables declaration//GEN-END:variables
}
