package com.wissensalt.sinarelektronik.masterdata.tipe.view;

import com.wissensalt.sinarelektronik.config.UserLevel;
import com.wissensalt.sinarelektronik.dao.TipeDAO;
import com.wissensalt.sinarelektronik.dao.impl.TipeDAOImpl;
import com.wissensalt.sinarelektronik.masterdata.tipe.controller.TipeController;
import com.wissensalt.sinarelektronik.masterdata.tipe.entity.TipeDTO;
import com.wissensalt.sinarelektronik.masterdata.tipe.model.TabelModelTipe;
import com.wissensalt.sinarelektronik.masterdata.tipe.model.TipeModel;
import com.wissensalt.sinarelektronik.masterdata.tipe.model.event.TipeListener;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fauzi
 */
public class TipeView extends javax.swing.JPanel implements TipeListener, ListSelectionListener{

    /**
     * Creates new form TipeView
     */
    
    private TipeController controller;
    private TabelModelTipe tabelmodelTipe;
    private TipeModel tipeModel;
    private final TipeDAO tipeDAO;

    
    public TipeView() {
        tipeDAO = new TipeDAOImpl();
        tabelmodelTipe = new TabelModelTipe();
        
        tipeModel = new TipeModel();
        tipeModel.setListener(this);
        
        controller = new TipeController();
        
        initComponents();
        
        tabelTipe.getSelectionModel().addListSelectionListener(this);
        
        tabelTipe.setModel(tabelmodelTipe);
        loadId();
        setLevel();
        txtTipe.requestFocus();
        LoadDatabase();
    
    }

    public void setLevel(){
        UserLevel userLevel = new UserLevel();
        String levelAktif = userLevel.getUserLevelActive();
        switch(levelAktif){
            case "Pemilik Toko":
                    txtTipe.setEnabled(true);
                    btTambah.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Administrator":
                    txtTipe.setEnabled(true);
                    btTambah.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Karyawan":
                    txtTipe.setEnabled(false);
                    btTambah.setEnabled(false);
                    btDelete.setEnabled(false);
                    btReset.setEnabled(false);
                    btUpdate.setEnabled(false);                
                break;                        
            default:;
        }
    }    
    
    public void loadId() {
        txtId.setText(String.valueOf((tipeDAO.getLastIdata()+1)));
        txtTipe.setText("");
        txtTipe.requestFocus();
    }

    public JTextField getTxtTipe() {
        return txtTipe;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTable getTabelTipe() {
        return tabelTipe;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTipe = new javax.swing.JTable();
        bawah = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        palingAtas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtTipe = new javax.swing.JTextField();
        setLayout(new java.awt.BorderLayout());

        atas.setLayout(new java.awt.BorderLayout());

        tabelTipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTipe);

        atas.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(atas, java.awt.BorderLayout.CENTER);

        bawah.setLayout(new java.awt.GridLayout(1, 4));

        btTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/tambah.png"))); // NOI18N
        btTambah.setMnemonic('T');
        btTambah.setFocusable(false);
        btTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        bawah.add(btTambah);

        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/update2.png"))); // NOI18N
        btUpdate.setMnemonic('U');
        btUpdate.setFocusable(false);
        btUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        bawah.add(btUpdate);

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/hapus.png"))); // NOI18N
        btDelete.setMnemonic('H');
        btDelete.setFocusable(false);
        btDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        bawah.add(btDelete);

        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/reset.png"))); // NOI18N
        btReset.setMnemonic('R');
        btReset.setFocusable(false);
        btReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        bawah.add(btReset);

        add(bawah, java.awt.BorderLayout.PAGE_END);

        palingAtas.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("Id :");
        jPanel1.add(jLabel2);

        jLabel1.setText("Tipe :");
        jPanel1.add(jLabel1);

        palingAtas.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        txtId.setEditable(false);
        jPanel2.add(txtId);

        txtTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipeActionPerformed(evt);
            }
        });
        jPanel2.add(txtTipe);

        palingAtas.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(palingAtas, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void delete(){
        controller.deleteTipe(this);
        controller.resetTipe(this);
        loadId();
    }
    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        delete();
    }

    private void update(){
        controller.updateTipe(this);
        loadId();
        txtTipe.requestFocus();        
    }            
    
    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        update();
    }
    
    public void tambah(){
        controller.insertTipe(this);
        loadId();
        txtTipe.setText("");
        txtTipe.requestFocus();                
    }
    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {
        tambah();
    }

    private void txtTipeActionPerformed(java.awt.event.ActionEvent evt) {
        tambah();        
    }

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {
        controller.resetTipe(this);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel palingAtas;
    private javax.swing.JTable tabelTipe;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTipe;

    @Override
    public void onChange(TipeModel model) {
        txtId.setText(model.getIdTipe());
        txtTipe.setText(model.getNamaTipe());
    }

    @Override
    public void onInsert(TipeDTO dto) {
        tabelmodelTipe.add(dto);
    }

    @Override
    public void onUpdate(TipeDTO dto) {
        int index = tabelTipe.getSelectedRow();
        tabelmodelTipe.set(index, dto);
    }

    @Override
    public void onDelete() {
        int index = tabelTipe.getSelectedRow();
        tabelmodelTipe.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        TipeDTO model = tabelmodelTipe.get(tabelTipe.getSelectedRow());
        txtId.setText(model.getIdTipe());
        txtTipe.setText(model.getNamaTipe());
    }

    private void LoadDatabase() {
        tabelmodelTipe.setList(tipeDAO.selectAllTipe());
    }
}
