/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wissensalt.sinarelektronik.masterdata.namabarang.view;

/**
 *
 * @author Fauzi
 */
public class JIFNamaBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFNamaBarang
     */
    public JIFNamaBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaBarangView1 = new com.wissensalt.sinarelektronik.masterdata.namabarang.view.NamaBarangView();

        setClosable(true);
        setTitle("Nama Barang");
        getContentPane().add(namaBarangView1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wissensalt.sinarelektronik.masterdata.namabarang.view.NamaBarangView namaBarangView1;
    // End of variables declaration//GEN-END:variables
}
