package com.wissensalt.sinarelektronik.masterdata.namabarang.view;

import com.wissensalt.sinarelektronik.config.UserLevel;
import com.wissensalt.sinarelektronik.dao.NamaBarangDAO;
import com.wissensalt.sinarelektronik.dao.impl.NamaBarangDAOImpl;
import com.wissensalt.sinarelektronik.masterdata.namabarang.controller.NamaBarangController;
import com.wissensalt.sinarelektronik.masterdata.namabarang.entity.NamaBarangDTO;
import com.wissensalt.sinarelektronik.masterdata.namabarang.model.NamaBarangModel;
import com.wissensalt.sinarelektronik.masterdata.namabarang.model.TabelModelNamaBarang;
import com.wissensalt.sinarelektronik.masterdata.namabarang.model.event.NamaBarangListener;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fauzi
 */
public class NamaBarangView extends javax.swing.JPanel implements NamaBarangListener, ListSelectionListener{

    /**
     * Creates new form NamaBarangView
     */
    private TabelModelNamaBarang tabelModelNamaBarang;
    private NamaBarangController namaBarangController;
    private NamaBarangDAO namaBarangDAO;
    
    public NamaBarangView() {
        namaBarangDAO = new NamaBarangDAOImpl();

        NamaBarangModel namaBarangModel = new NamaBarangModel();
        namaBarangModel.setListener(this);
        
        namaBarangController = new NamaBarangController();
        namaBarangController.setModel(namaBarangModel);
        
        initComponents();
        
        tabelModelNamaBarang = new TabelModelNamaBarang();
        tabelNamaBarang.setModel(tabelModelNamaBarang);
        tabelNamaBarang.getSelectionModel().addListSelectionListener(this);
        loadDatabase();
        loadId();
        setLevel();
        txtNamaBarang.requestFocus();
    }

    public void setLevel(){
        UserLevel userLevel = new UserLevel();
        String levelAktif = userLevel.getUserLevelActive();
        switch(levelAktif){
            case "Pemilik Toko":
                    txtNamaBarang.setEnabled(true);
                    btTambah.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Administrator":
                    txtNamaBarang.setEnabled(true);
                    btTambah.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Karyawan":
                    txtNamaBarang.setEnabled(false);
                    btTambah.setEnabled(false);
                    btDelete.setEnabled(false);
                    btReset.setEnabled(false);
                    btUpdate.setEnabled(false);                
                break;                        
            default:;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atas = new javax.swing.JPanel();
        kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kanan = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        tengah = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNamaBarang = new javax.swing.JTable();
        bawah = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btReset = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        atas.setLayout(new java.awt.GridLayout(1, 2));

        kiri.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setText("Id :");
        kiri.add(jLabel1);

        jLabel2.setText("Nama Barang :");
        kiri.add(jLabel2);

        atas.add(kiri);

        kanan.setLayout(new java.awt.GridLayout(2, 0));

        txtId.setEditable(false);
        kanan.add(txtId);
        kanan.add(txtNamaBarang);

        atas.add(kanan);

        add(atas, java.awt.BorderLayout.PAGE_START);

        tengah.setLayout(new java.awt.BorderLayout());

        tabelNamaBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelNamaBarang);

        tengah.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(tengah, java.awt.BorderLayout.CENTER);

        bawah.setLayout(new java.awt.GridLayout(1, 4));

        btTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/tambah2.png"))); // NOI18N
        btTambah.setMnemonic('T');
        btTambah.setFocusable(false);
        btTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        bawah.add(btTambah);

        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/update2.png"))); // NOI18N
        btUpdate.setMnemonic('U');
        btUpdate.setFocusable(false);
        btUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        bawah.add(btUpdate);

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/hapus.png"))); // NOI18N
        btDelete.setMnemonic('H');
        btDelete.setFocusable(false);
        btDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        bawah.add(btDelete);

        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/reset.png"))); // NOI18N
        btReset.setMnemonic('R');
        btReset.setFocusable(false);
        btReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        bawah.add(btReset);

        add(bawah, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTabelNamaBarang() {
        return tabelNamaBarang;
    }

    public void setTabelNamaBarang(JTable tabelNamaBarang) {
        this.tabelNamaBarang = tabelNamaBarang;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextField getTxtNamaBarang() {
        return txtNamaBarang;
    }

    public void setTxtNamaBarang(JTextField txtNamaBarang) {
        this.txtNamaBarang = txtNamaBarang;
    }

    public void tambah(){
        namaBarangController.insertNamaBarang(this);
    }
    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {
        tambah();
    }

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        namaBarangController.updateNamaBarang(this);
    }

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        namaBarangController.deletenamabarang(this);
    }

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {
        namaBarangController.resetNamaBarang(this);
        txtNamaBarang.setText("");
        txtNamaBarang.requestFocus();
    }

    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kanan;
    private javax.swing.JPanel kiri;
    private javax.swing.JTable tabelNamaBarang;
    private javax.swing.JPanel tengah;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNamaBarang;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(NamaBarangModel model) {
        txtId.setText(String.valueOf(model.getId()));
        txtNamaBarang.setText(model.getNamaBarang());
    }

    @Override
    public void onInsert(NamaBarangDTO namaBarangDTO) {
        tabelModelNamaBarang.add(namaBarangDTO);
    }

    @Override
    public void onUpdate(NamaBarangDTO namaBarangDTO) {
        int index = tabelNamaBarang.getSelectedRow();
        tabelModelNamaBarang.set(index, namaBarangDTO);
    }

    @Override
    public void onDelete() {
        int index = tabelNamaBarang.getSelectedRow();
        tabelModelNamaBarang.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        NamaBarangDTO nb = tabelModelNamaBarang.get(tabelNamaBarang.getSelectedRow());
        txtId.setText(String.valueOf(nb.getId()));
        txtNamaBarang.setText(nb.getNamabarang());
    }
    
    public void loadDatabase(){
        tabelModelNamaBarang.setList(namaBarangDAO.selectAllNamaBarang());
    }
    
    public void loadId(){
        txtId.setText(String.valueOf(namaBarangDAO.getLastId()));
        txtNamaBarang.requestFocus();
    }
}
