/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.masterdata.supplier.view;

/**
 *
 * @author Fauzi
 */
public class JIFSupplierView extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFSupplierView
     */
    public JIFSupplierView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            supplierView1 = new Sinarelektronikapp.masterdata.supplier.view.supplierView();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        } catch (Sinarelektronikapp.masterdata.supplier.error.supplierException e2) {
            e2.printStackTrace();
        }

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manajemen Supplier");
        setPreferredSize(new java.awt.Dimension(800, 500));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().add(supplierView1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Sinarelektronikapp.masterdata.supplier.view.supplierView supplierView1;
    // End of variables declaration//GEN-END:variables
}
