/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.retur.barangkecil.view;

/**
 *
 * @author Fauzi
 */
public class JIFPRosesRetur2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFPRosesRetur2
     */
    public JIFPRosesRetur2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prosesRetur1 = new Sinarelektronikapp.retur.barangkecil.view.ProsesRetur();

        setClosable(true);
        setForeground(java.awt.Color.white);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Proses Retur Barang Kecil");
        getContentPane().add(prosesRetur1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Sinarelektronikapp.retur.barangkecil.view.ProsesRetur prosesRetur1;
    // End of variables declaration//GEN-END:variables
}
