/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.ReturBarangBesar.transaksi.view;

/**
 *
 * @author Fauzi
 */
public class JIFPRosesReturBB extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFPRosesReturBB
     */
    public JIFPRosesReturBB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prosesRetur2 = new Sinarelektronikapp.ReturBarangBesar.transaksi.view.ProsesRetur();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Proses Retur");
        getContentPane().add(prosesRetur2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Sinarelektronikapp.ReturBarangBesar.transaksi.view.ProsesRetur prosesRetur2;
    // End of variables declaration//GEN-END:variables
}
