/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wissensalt.sinarelektronik.masterdata.supplier.view;

/**
 *
 * @author Fauzi
 */
public class JIFSupplierView extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFSupplierView
     */
    public JIFSupplierView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        supplierView1 = new SupplierView();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manajemen Supplier");
        setPreferredSize(new java.awt.Dimension(800, 500));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().add(supplierView1, java.awt.BorderLayout.CENTER);

        pack();
    }

    private SupplierView supplierView1;

}
