/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wissensalt.sinarelektronik.masterdata.barangtoko.stokreminder.view;

/**
 *
 * @author Fauzi
 */
public class JIFReminderViewToko extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFReminderViewToko
     */
    public JIFReminderViewToko() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reminderView1 = new com.wissensalt.sinarelektronik.masterdata.barangbesar.stokreminder.view.ReminderView();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Stok Ulang Barang Toko");
        getContentPane().add(reminderView1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wissensalt.sinarelektronik.masterdata.barangbesar.stokreminder.view.ReminderView reminderView1;
    // End of variables declaration//GEN-END:variables
}
