package com.wissensalt.sinarelektronik.masterdata.satuan.view;

import com.wissensalt.sinarelektronik.config.UserLevel;
import com.wissensalt.sinarelektronik.dao.SatuanDAO;
import com.wissensalt.sinarelektronik.dao.impl.SatuanDAOImpl;
import com.wissensalt.sinarelektronik.masterdata.satuan.controller.SatuanController;
import com.wissensalt.sinarelektronik.masterdata.satuan.entity.SatuanDTO;
import com.wissensalt.sinarelektronik.masterdata.satuan.model.SatuanModel;
import com.wissensalt.sinarelektronik.masterdata.satuan.model.TabelModelSatuan;
import com.wissensalt.sinarelektronik.masterdata.satuan.model.event.satuanListener;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fauzi
 */
public class SatuanView extends javax.swing.JPanel implements satuanListener, ListSelectionListener{

    private TabelModelSatuan modelSatuan ;
    private SatuanController controller ;
    private SatuanDAO satuanDAO;

    public SatuanView() {
        satuanDAO = new SatuanDAOImpl();
        modelSatuan = new TabelModelSatuan();

        SatuanModel model = new SatuanModel();
        model.setListener(this);

        controller = new SatuanController();
        controller.setModel(model);

        initComponents();

        tabelSatuan.setModel(modelSatuan);
        tabelSatuan.getSelectionModel().addListSelectionListener(this);
        loadId();
        loadDatabase();
        setLevel();
    }

    public JTable getTabelSatuan() {
        return tabelSatuan;
    }

    public JTextField getTxtId() {
        return txtId;
    }


    public JTextField getTxtSatuan() {
        return txtSatuan;
    }

    public void setLevel(){
        UserLevel userLevel = new UserLevel();
        String levelAktif = userLevel.getUserLevelActive();
        switch(levelAktif){
            case "Pemilik Toko":
                txtSatuan.setEnabled(true);
                btTambah.setEnabled(true);
                btDelete.setEnabled(true);
                btReset.setEnabled(true);
                btUpdate.setEnabled(true);
                break;
            case "Administrator":
                txtSatuan.setEnabled(true);
                btTambah.setEnabled(true);
                btDelete.setEnabled(true);
                btReset.setEnabled(true);
                btUpdate.setEnabled(true);
                break;
            case "Karyawan":
                txtSatuan.setEnabled(false);
                btTambah.setEnabled(false);
                btDelete.setEnabled(false);
                btReset.setEnabled(false);
                btUpdate.setEnabled(false);
                break;
            default:;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSatuan = new javax.swing.JTable();
        bawah = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        palingAtas = new javax.swing.JPanel();
        kiri = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kanan = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtSatuan = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        atas.setLayout(new java.awt.BorderLayout());

        tabelSatuan.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(tabelSatuan);

        atas.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(atas, java.awt.BorderLayout.CENTER);

        bawah.setLayout(new java.awt.GridLayout(1, 4));

        btTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/tambah.png"))); // NOI18N
        btTambah.setMnemonic('T');
        btTambah.setFocusable(false);
        btTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        bawah.add(btTambah);

        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/update2.png"))); // NOI18N
        btUpdate.setMnemonic('U');
        btUpdate.setFocusable(false);
        btUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        bawah.add(btUpdate);

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/hapus.png"))); // NOI18N
        btDelete.setMnemonic('H');
        btDelete.setFocusable(false);
        btDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        bawah.add(btDelete);

        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/reset.png"))); // NOI18N
        btReset.setMnemonic('R');
        btReset.setFocusable(false);
        btReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        bawah.add(btReset);

        add(bawah, java.awt.BorderLayout.PAGE_END);

        palingAtas.setLayout(new java.awt.BorderLayout());

        kiri.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("id :");
        kiri.add(jLabel2);

        jLabel1.setText("Satuan :");
        kiri.add(jLabel1);

        palingAtas.add(kiri, java.awt.BorderLayout.WEST);

        kanan.setLayout(new java.awt.GridLayout(2, 0));

        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFocusGained(evt);
            }
        });
        kanan.add(txtId);

        txtSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatuanActionPerformed(evt);
            }
        });
        kanan.add(txtSatuan);

        palingAtas.add(kanan, java.awt.BorderLayout.CENTER);

        add(palingAtas, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        controller.deletesatuan(this);
        controller.resetsatuan(this);
        loadId();
    }

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        controller.updatesatuan(this);
        loadId();
    }

    public void tambah(){
        controller.insertsatuan(this);
        loadId();
        txtSatuan.setText("");
        txtSatuan.requestFocus();
    }
    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {
        tambah();
    }

    private void txtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusGained
        loadId();
    }

    private void txtSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatuanActionPerformed
        tambah();
    }

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        controller.resetsatuan(this);
    }

    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kanan;
    private javax.swing.JPanel kiri;
    private javax.swing.JPanel palingAtas;
    private javax.swing.JTable tabelSatuan;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtSatuan;

    @Override
    public void onChange(SatuanModel model) {
        txtId.setText(model.getIdsatuan());
        txtSatuan.setText(model.getNamaSatuan());
    }

    @Override
    public void onInsert(SatuanDTO SatuanDTO) {
        modelSatuan.add(SatuanDTO);
    }

    @Override
    public void onUpdate(SatuanDTO SatuanDTO) {
        int index = tabelSatuan.getSelectedRow();
        modelSatuan.set(index, SatuanDTO);
    }

    @Override
    public void onDelete() {
        int index = tabelSatuan.getSelectedRow();
        modelSatuan.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        SatuanDTO SatuanDTO = modelSatuan.get(tabelSatuan.getSelectedRow());

        txtId.setText(SatuanDTO.getIdsatuan());
        txtSatuan.setText(SatuanDTO.getNamaSatuan());
    }

    public void loadId() {
        txtId.setText(String.valueOf(satuanDAO.getLastId()));
        txtSatuan.requestFocus();
    }

    public void loadDatabase(){
        modelSatuan.setList(satuanDAO.selectAllSatuan());
    }
}
