/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.penjualan.garansi.view;

import Sinarelektronikapp.penjualan.garansi.controller.GaransiController;
import Sinarelektronikapp.penjualan.garansi.database.GaransiDatabase;
import Sinarelektronikapp.penjualan.garansi.entity.Garansi;
import Sinarelektronikapp.penjualan.garansi.error.GaransiException;
import Sinarelektronikapp.penjualan.garansi.event.GaransiListener;
import Sinarelektronikapp.penjualan.garansi.model.GaransiModel;
import Sinarelektronikapp.penjualan.garansi.model.TabelModelGaransi;
import Sinarelektronikapp.penjualan.garansi.service.GaransiDao;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fauzi
 */
public class GaransiView extends javax.swing.JPanel implements GaransiListener, ListSelectionListener{

    /**
     * Creates new form GaransiView
     */
    
    TabelModelGaransi tabelModelGaransi;
    
    GaransiController controller;
    
    GaransiModel garansiModel;
    
    public GaransiView() {
        garansiModel = new GaransiModel();
        garansiModel.setListener(this);
        
        controller = new GaransiController();
        controller.setGaransiModel(garansiModel);
                
        initComponents();                
        tabelModelGaransi = new TabelModelGaransi();
        tabelGaransi.setModel(tabelModelGaransi);
        tabelGaransi.getSelectionModel().addListSelectionListener(this);
        loadDatabase();
    }

    public JComboBox getCmbStatus() {
        return cmbStatus;
    }

    public JDateChooser getjDateMasaAkhir() {
        return jDateMasaAkhir;
    }

    public JTable getTabelGaransi() {
        return tabelGaransi;
    }

    public JTextField getTxtIdGaransi() {
        return txtIdGaransi;
    }

    public JTextField getTxtJumlah() {
        return txtJumlah;
    }

    public JTextField getTxtNamaBarang() {
        return txtNamaBarang;
    }

    public JComboBox getCmbCari() {
        return cmbCari;
    }

    public JComboBox getCmbUrut() {
        return cmbUrut;
    }

    public JTextField getTxtKataKunci() {
        return txtKataKunci;
    }

       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        satu = new javax.swing.JPanel();
        up = new javax.swing.JPanel();
        panelBackgroundUp = new Sinarelektronikapp.swingResource.panelGradUser();
        kiri = new javax.swing.JPanel();
        labeling4 = new Sinarelektronikapp.swingResource.labeling();
        labeling5 = new Sinarelektronikapp.swingResource.labeling();
        labeling6 = new Sinarelektronikapp.swingResource.labeling();
        kanan = new javax.swing.JPanel();
        atas = new javax.swing.JPanel();
        txtKataKunci = new javax.swing.JTextField();
        btCari = new javax.swing.JButton();
        tengah = new javax.swing.JPanel();
        cmbCari = new javax.swing.JComboBox();
        bawah = new javax.swing.JPanel();
        cmbUrut = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelGaransi = new javax.swing.JTable();
        below = new javax.swing.JPanel();
        dua = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdGaransi = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateMasaAkhir = new com.toedter.calendar.JDateChooser();
        cmbStatus = new javax.swing.JComboBox();
        last = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btReset = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        satu.setMinimumSize(new java.awt.Dimension(304, 350));
        satu.setPreferredSize(new java.awt.Dimension(400, 350));
        satu.setLayout(new java.awt.BorderLayout());

        up.setLayout(new java.awt.BorderLayout());

        panelBackgroundUp.setLayout(new java.awt.BorderLayout());

        kiri.setOpaque(false);
        kiri.setLayout(new java.awt.GridLayout(3, 1));

        labeling4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labeling4.setText("Masukkan kata kunci :");
        kiri.add(labeling4);

        labeling5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labeling5.setText("Cari data berdasarkan :");
        kiri.add(labeling5);

        labeling6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labeling6.setText("Urutkan data berdasarkan :");
        kiri.add(labeling6);

        panelBackgroundUp.add(kiri, java.awt.BorderLayout.WEST);

        kanan.setOpaque(false);
        kanan.setLayout(new java.awt.GridLayout(3, 0));

        atas.setOpaque(false);

        btCari.setText("cari");
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout atasLayout = new javax.swing.GroupLayout(atas);
        atas.setLayout(atasLayout);
        atasLayout.setHorizontalGroup(
            atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atasLayout.createSequentialGroup()
                .addComponent(txtKataKunci, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCari, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        atasLayout.setVerticalGroup(
            atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtKataKunci)
            .addComponent(btCari, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        kanan.add(atas);

        tengah.setOpaque(false);
        tengah.setLayout(new java.awt.BorderLayout());

        cmbCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Id Garansi", "Nama Barang", "Jumlah", "Masa Akhir", "Status" }));
        cmbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCariActionPerformed(evt);
            }
        });
        tengah.add(cmbCari, java.awt.BorderLayout.CENTER);

        kanan.add(tengah);

        bawah.setOpaque(false);
        bawah.setLayout(new java.awt.BorderLayout());

        cmbUrut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Id Garansi", "Nama Barang", "Jumlah", "Masa Akhir", "Status" }));
        cmbUrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUrutActionPerformed(evt);
            }
        });
        bawah.add(cmbUrut, java.awt.BorderLayout.CENTER);

        kanan.add(bawah);

        panelBackgroundUp.add(kanan, java.awt.BorderLayout.CENTER);

        up.add(panelBackgroundUp, java.awt.BorderLayout.CENTER);

        satu.add(up, java.awt.BorderLayout.PAGE_START);

        tabelGaransi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelGaransi);

        satu.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(satu, java.awt.BorderLayout.PAGE_START);

        below.setLayout(new java.awt.BorderLayout());

        dua.setPreferredSize(new java.awt.Dimension(400, 120));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Id Garansi :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nama Barang :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Jumlah :");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Masa Akhir");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Status :");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Progress", "Habis" }));

        javax.swing.GroupLayout duaLayout = new javax.swing.GroupLayout(dua);
        dua.setLayout(duaLayout);
        duaLayout.setHorizontalGroup(
            duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(duaLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(duaLayout.createSequentialGroup()
                        .addGroup(duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGroup(duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, duaLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(138, 138, 138))
                                .addGroup(duaLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtIdGaransi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, duaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(duaLayout.createSequentialGroup()
                                        .addComponent(jDateMasaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(duaLayout.createSequentialGroup()
                                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        duaLayout.setVerticalGroup(
            duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(duaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdGaransi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jDateMasaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(duaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        below.add(dua, java.awt.BorderLayout.CENTER);

        last.setLayout(new java.awt.GridLayout(1, 4));

        btTambah.setText("Tambah");
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        last.add(btTambah);

        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        last.add(btUpdate);

        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        last.add(btDelete);

        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        last.add(btReset);

        below.add(last, java.awt.BorderLayout.PAGE_END);

        add(below, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
        controller.search(this);
    }//GEN-LAST:event_btCariActionPerformed

    private void cmbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCariActionPerformed

    private void cmbUrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUrutActionPerformed
            controller.sort(this);
    }//GEN-LAST:event_cmbUrutActionPerformed

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
        if(jDateMasaAkhir.getDate() == null){
            JOptionPane.showMessageDialog(null, "Masa Akhir masih kosong");
            jDateMasaAkhir.requestFocus();
            return;
        }
        controller.insertGaransi(this);
        controller.resetGaransi(this);
    }//GEN-LAST:event_btTambahActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        if(jDateMasaAkhir.getDate() == null){
            JOptionPane.showMessageDialog(null, "Masa Akhir masih kosong");
            jDateMasaAkhir.requestFocus();
            return;
        }        
        controller.updateGaransi(this);
        controller.resetGaransi(this);
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        controller.deleteGaransi(this);
        controller.resetGaransi(this);
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        controller.resetGaransi(this);
    }//GEN-LAST:event_btResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.JPanel below;
    private javax.swing.JButton btCari;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUpdate;
    private javax.swing.JComboBox cmbCari;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JComboBox cmbUrut;
    private javax.swing.JPanel dua;
    private com.toedter.calendar.JDateChooser jDateMasaAkhir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kanan;
    private javax.swing.JPanel kiri;
    private Sinarelektronikapp.swingResource.labeling labeling4;
    private Sinarelektronikapp.swingResource.labeling labeling5;
    private Sinarelektronikapp.swingResource.labeling labeling6;
    private javax.swing.JPanel last;
    private Sinarelektronikapp.swingResource.panelGradUser panelBackgroundUp;
    private javax.swing.JPanel satu;
    private javax.swing.JTable tabelGaransi;
    private javax.swing.JPanel tengah;
    private javax.swing.JTextField txtIdGaransi;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKataKunci;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JPanel up;
    // End of variables declaration//GEN-END:variables

    Date date=new Date();        
    
    SimpleDateFormat formatTanggal2=new SimpleDateFormat("dd-MM-YYYY");
    
    @Override
    public void onChange(GaransiModel model) {
        txtIdGaransi.setText(model.getIdTransaksi());
        txtNamaBarang.setText(model.getNamaBarang());
        txtJumlah.setText(String.valueOf(model.getJumlah()));
        cmbStatus.setSelectedItem(model.getStatus());
        /*Date tanggal = new Date(model.getMasaakhir());
        jDateMasaAkhir.setDate(tanggal);*/
    }

    @Override
    public void onInsert(Garansi garansi) {
        tabelModelGaransi.add(garansi);
    }

    @Override
    public void onUpdate(Garansi garansi) {
        int index = tabelGaransi.getSelectedRow();
        tabelModelGaransi.set(index, garansi);
    }

    @Override
    public void onDelete() {
        int index = tabelGaransi.getSelectedRow();
        tabelModelGaransi.remove(index);
    }

    @Override
    public void onSearch(List list) {
        tabelModelGaransi.setList(list);
    }

    @Override
    public void onSort(List list) {
        tabelModelGaransi.setList(list);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try{
            Garansi garansi = tabelModelGaransi.get(tabelGaransi.getSelectedRow());
            txtIdGaransi.setText(garansi.getIdTransaksi());
            txtNamaBarang.setText(garansi.getNamaBarang());
            txtJumlah.setText(String.valueOf(garansi.getJumlah()));
            /*Date masaakhir = new Date(garansi.getMasaakhir());
            jDateMasaAkhir.setDate(masaakhir);*/
            cmbStatus.setSelectedItem(garansi.getStatus());
        }catch(IndexOutOfBoundsException ioobe){
            
        }
    }
    
    public void loadDatabase(){
        GaransiDao dao = GaransiDatabase.getGaransiDao();
        try {
            tabelModelGaransi.setList(dao.getAllGaransi());
        } catch (GaransiException ex) {
            Logger.getLogger(GaransiView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
