/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.masterData.tipe.view;

/**
 *
 * @author Fauzi
 */
public class JIFTipeView extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFTipeView
     */
    public JIFTipeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            tipeView2 = new Sinarelektronikapp.masterData.tipe.view.TipeView();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        } catch (Sinarelektronikapp.masterData.tipe.error.TipeException e2) {
            e2.printStackTrace();
        }

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manajemen Tipe Barang");
        setPreferredSize(new java.awt.Dimension(400, 300));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().add(tipeView2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Sinarelektronikapp.masterData.tipe.view.TipeView tipeView2;
    // End of variables declaration//GEN-END:variables
}
