/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.masterdata.tipe.view;

import Sinarelektronikapp.config.UserLevel;
import Sinarelektronikapp.masterdata.tipe.controller.tipeController;
import Sinarelektronikapp.masterdata.tipe.database.tipeDatabase;
import Sinarelektronikapp.masterdata.tipe.entity.tipe;
import Sinarelektronikapp.masterdata.tipe.error.TipeException;
import Sinarelektronikapp.masterdata.tipe.model.event.tipeListener;
import Sinarelektronikapp.masterdata.tipe.model.tabelModelTipe;
import Sinarelektronikapp.masterdata.tipe.model.tipeModel;
import Sinarelektronikapp.masterdata.tipe.service.tipeDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fauzi
 */
public class TipeView extends javax.swing.JPanel implements tipeListener, ListSelectionListener{

    /**
     * Creates new form TipeView
     */
    
    private tipeController controller;
    
    private tabelModelTipe tabelmodelTipe;
    
    private tipeModel model;
    
    public TipeView() throws SQLException, TipeException {
        tabelmodelTipe = new tabelModelTipe();
        
        model = new tipeModel();
        model.setListener(this);
        
        controller = new tipeController(model);
        
        initComponents();
        
        tabelTipe.getSelectionModel().addListSelectionListener(this);
        
        tabelTipe.setModel(tabelmodelTipe);
        try {
            loadId();
        } catch (TipeException ex) {
            Logger.getLogger(TipeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        setLevel();
        txtTipe.requestFocus();
        LoadDatabase();

/*    ActionListener taskPerformer = new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent evt) {        
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher() {
              @Override
              public boolean dispatchKeyEvent(KeyEvent e) {
                  if(e.getID() == KeyEvent.KEY_PRESSED){
                      if(e.getKeyCode() == KeyEvent.VK_F1){
                          tambah();
                      }else if(e.getKeyCode() == KeyEvent.VK_F2){
                          update();
                      }else if(e.getKeyCode() == KeyEvent.VK_F3){
                          delete();
                      }
                  }
                return false;
              }
          });
      }
    };
    // Timer
    new Timer(1000, taskPerformer).start();        */
    
    }

    public void setLevel(){
        UserLevel userLevel = new UserLevel();
        String levelAktif = userLevel.getUserLevelActive();
        switch(levelAktif){
            case "Pemilik Toko":
                    txtTipe.setEnabled(true);
                    btTambah.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Administrator":
                    txtTipe.setEnabled(true);
                    btTambah.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Karyawan":
                    txtTipe.setEnabled(false);
                    btTambah.setEnabled(false);
                    btDelete.setEnabled(false);
                    btReset.setEnabled(false);
                    btUpdate.setEnabled(false);                
                break;                        
            default:;
        }
    }    
    
    public void loadId() throws SQLException, TipeException{
        txtId.setText(String.valueOf(getLastId()));
        txtTipe.setText("");
        txtTipe.requestFocus();
    }
    
    public int getLastId() throws SQLException, TipeException{
        tipeDao dao=tipeDatabase.getTipeDao();
        return dao.getLastIdata()+1;
    }
    public JTextField getTxtTipe() {
        return txtTipe;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTable getTabelTipe() {
        return tabelTipe;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTipe = new javax.swing.JTable();
        bawah = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        palingAtas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtTipe = new javax.swing.JTextField();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        atas.setLayout(new java.awt.BorderLayout());

        tabelTipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTipe);

        atas.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(atas, java.awt.BorderLayout.CENTER);

        bawah.setLayout(new java.awt.GridLayout(1, 4));

        btTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/tambah.png"))); // NOI18N
        btTambah.setMnemonic('T');
        btTambah.setFocusable(false);
        btTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        bawah.add(btTambah);

        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/update2.png"))); // NOI18N
        btUpdate.setMnemonic('U');
        btUpdate.setFocusable(false);
        btUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        bawah.add(btUpdate);

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/hapus.png"))); // NOI18N
        btDelete.setMnemonic('H');
        btDelete.setFocusable(false);
        btDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        bawah.add(btDelete);

        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/reset.png"))); // NOI18N
        btReset.setMnemonic('R');
        btReset.setFocusable(false);
        btReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        bawah.add(btReset);

        add(bawah, java.awt.BorderLayout.PAGE_END);

        palingAtas.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("Id :");
        jPanel1.add(jLabel2);

        jLabel1.setText("Tipe :");
        jPanel1.add(jLabel1);

        palingAtas.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        txtId.setEditable(false);
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFocusGained(evt);
            }
        });
        jPanel2.add(txtId);

        txtTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipeActionPerformed(evt);
            }
        });
        jPanel2.add(txtTipe);

        palingAtas.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(palingAtas, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void delete(){
        controller.deleteTipe(this);
        controller.resetTipe(this);
        try {
            loadId();
        } catch (SQLException ex) {
            Logger.getLogger(TipeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TipeException ex) {
            Logger.getLogger(TipeView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btDeleteActionPerformed

    private void update(){
        controller.updateTipe(this);
        try {
            loadId();
        } catch (SQLException ex) {
            Logger.getLogger(TipeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TipeException ex) {
            Logger.getLogger(TipeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTipe.requestFocus();        
    }            
    
    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btUpdateActionPerformed
    
    public void tambah(){
        controller.insertTipe(this);
        try {
            loadId();
        } catch (SQLException ex) {
            Logger.getLogger(TipeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TipeException ex) {
            Logger.getLogger(TipeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            loadId();
        } catch (SQLException ex) {
            Logger.getLogger(TipeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TipeException ex) {
            Logger.getLogger(TipeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtTipe.setText("");
        txtTipe.requestFocus();                
    }
    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:        
        tambah();
    }//GEN-LAST:event_btTambahActionPerformed

    private void txtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusGained

    }//GEN-LAST:event_txtIdFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void txtTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipeActionPerformed
        // TODO add your handling code here:
        tambah();        
    }//GEN-LAST:event_txtTipeActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        controller.resetTipe(this);
    }//GEN-LAST:event_btResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel palingAtas;
    private javax.swing.JTable tabelTipe;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTipe;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(tipeModel model) {
        txtId.setText(model.getIdtipe());
        txtTipe.setText(model.getNamaTipe());
    }

    @Override
    public void onInsert(tipe tipe) {
        tabelmodelTipe.add(tipe);
    }

    @Override
    public void onUpdate(tipe tipe) {
        int index = tabelTipe.getSelectedRow();
        tabelmodelTipe.set(index, tipe);
    }

    @Override
    public void onDelete() {
        int index = tabelTipe.getSelectedRow();
        tabelmodelTipe.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            tipe model = tabelmodelTipe.get(tabelTipe.getSelectedRow());
            txtId.setText(model.getIdtipe());
            txtTipe.setText(model.getNamaTipe());
        } catch (IndexOutOfBoundsException exception) {
            //JOptionPane.showMessageDialog(null, "Error pada overriding value Changed dengan pesan "+e);
        }
    }

    public void LoadDatabase() throws SQLException, SQLException, TipeException {
        tipeDao  dao = tipeDatabase.getTipeDao();
        tabelmodelTipe.setList(dao.selectAllTipe());
    }
}
