/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.masterData.namabarang.view;

import Sinarelektronikapp.config.UserLevel;
import Sinarelektronikapp.masterData.namabarang.Entity.NamaBarang;
import Sinarelektronikapp.masterData.namabarang.controller.NamaBarangController;
import Sinarelektronikapp.masterData.namabarang.database.NamaBarangDatabase;
import Sinarelektronikapp.masterData.namabarang.error.NamaBarangException;
import Sinarelektronikapp.masterData.namabarang.model.NamaBarangModel;
import Sinarelektronikapp.masterData.namabarang.model.TabelModelNamaBarang;
import Sinarelektronikapp.masterData.namabarang.model.event.NamaBarangListener;
import Sinarelektronikapp.masterData.namabarang.service.NamaBarangDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fauzi
 */
public class NamaBarangView extends javax.swing.JPanel implements NamaBarangListener, ListSelectionListener{

    /**
     * Creates new form NamaBarangView
     */
    private TabelModelNamaBarang tabelModelNamaBarang;
    
    private NamaBarangModel namaBarangModel;
    
    private NamaBarangController namaBarangController;
    
    public NamaBarangView() {
        namaBarangModel = new NamaBarangModel();
        namaBarangModel.setListener(this);
        
        namaBarangController = new NamaBarangController();
        namaBarangController.setModel(namaBarangModel);
        
        initComponents();
        
        tabelModelNamaBarang = new TabelModelNamaBarang();
        tabelNamaBarang.setModel(tabelModelNamaBarang);
        tabelNamaBarang.getSelectionModel().addListSelectionListener(this);
        loadDatabase();
        loadId();
        setLevel();
        txtNamaBarang.requestFocus();
    }

    public void setLevel(){
        UserLevel userLevel = new UserLevel();
        String levelAktif = userLevel.getUserLevelActive();
        switch(levelAktif){
            case "Pemilik Toko":
                    txtNamaBarang.setEnabled(true);
                    btTambah.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Administrator":
                    txtNamaBarang.setEnabled(true);
                    btTambah.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Karyawan":
                    txtNamaBarang.setEnabled(false);
                    btTambah.setEnabled(false);
                    btDelete.setEnabled(false);
                    btReset.setEnabled(false);
                    btUpdate.setEnabled(false);                
                break;                        
            default:;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atas = new javax.swing.JPanel();
        kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kanan = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        tengah = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNamaBarang = new javax.swing.JTable();
        bawah = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btReset = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        atas.setLayout(new java.awt.GridLayout(1, 2));

        kiri.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setText("Id :");
        kiri.add(jLabel1);

        jLabel2.setText("Nama Barang :");
        kiri.add(jLabel2);

        atas.add(kiri);

        kanan.setLayout(new java.awt.GridLayout(2, 0));

        txtId.setEditable(false);
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFocusGained(evt);
            }
        });
        kanan.add(txtId);

        txtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangActionPerformed(evt);
            }
        });
        kanan.add(txtNamaBarang);

        atas.add(kanan);

        add(atas, java.awt.BorderLayout.PAGE_START);

        tengah.setLayout(new java.awt.BorderLayout());

        tabelNamaBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelNamaBarang);

        tengah.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(tengah, java.awt.BorderLayout.CENTER);

        bawah.setLayout(new java.awt.GridLayout(1, 4));

        btTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/tambah2.png"))); // NOI18N
        btTambah.setMnemonic('T');
        btTambah.setFocusable(false);
        btTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        bawah.add(btTambah);

        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/update2.png"))); // NOI18N
        btUpdate.setMnemonic('U');
        btUpdate.setFocusable(false);
        btUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        bawah.add(btUpdate);

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/hapus.png"))); // NOI18N
        btDelete.setMnemonic('H');
        btDelete.setFocusable(false);
        btDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        bawah.add(btDelete);

        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/reset.png"))); // NOI18N
        btReset.setMnemonic('R');
        btReset.setFocusable(false);
        btReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        bawah.add(btReset);

        add(bawah, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTabelNamaBarang() {
        return tabelNamaBarang;
    }

    public void setTabelNamaBarang(JTable tabelNamaBarang) {
        this.tabelNamaBarang = tabelNamaBarang;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextField getTxtNamaBarang() {
        return txtNamaBarang;
    }

    public void setTxtNamaBarang(JTextField txtNamaBarang) {
        this.txtNamaBarang = txtNamaBarang;
    }
    private void txtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusGained
        /*try {
            // TODO add your handling code here:
            loadID();
        } catch (SQLException ex) {
            Logger.getLogger(MerekView2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (merekException ex) {
            Logger.getLogger(MerekView2.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_txtIdFocusGained

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    public void tambah(){
        namaBarangController.insertNamaBarang(this);
    }
    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_btTambahActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        namaBarangController.updateNamaBarang(this);
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        namaBarangController.deletenamabarang(this);
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        namaBarangController.resetNamaBarang(this);
        txtNamaBarang.setText("");
        txtNamaBarang.requestFocus();
    }//GEN-LAST:event_btResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kanan;
    private javax.swing.JPanel kiri;
    private javax.swing.JTable tabelNamaBarang;
    private javax.swing.JPanel tengah;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNamaBarang;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(NamaBarangModel model) {
        txtId.setText(String.valueOf(model.getId()));
        txtNamaBarang.setText(model.getNamaBarang());
    }

    @Override
    public void onInsert(NamaBarang namaBarang) {
        tabelModelNamaBarang.add(namaBarang);
    }

    @Override
    public void onUpdate(NamaBarang namaBarang) {
        int index = tabelNamaBarang.getSelectedRow();
        tabelModelNamaBarang.set(index, namaBarang);
    }

    @Override
    public void onDelete() {
        int index = tabelNamaBarang.getSelectedRow();
        tabelModelNamaBarang.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try{
            NamaBarang nb = tabelModelNamaBarang.get(tabelNamaBarang.getSelectedRow());
            txtId.setText(String.valueOf(nb.getId()));
            txtNamaBarang.setText(nb.getNamabarang());
        }catch(IndexOutOfBoundsException boundsException){
            
        }
    }
    
    public void loadDatabase(){
        try {
            NamaBarangDao barangDao = NamaBarangDatabase.getNamaBarangDao();
            try {
                tabelModelNamaBarang.setList(barangDao.selectAllNamaBarang());
            } catch (NamaBarangException ex) {
                Logger.getLogger(NamaBarangView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NamaBarangView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void loadId(){
        NamaBarangDao dao;
        int lastid = 0;
        try {
            dao = NamaBarangDatabase.getNamaBarangDao();
            try {
                lastid=dao.getLastId();
            } catch (NamaBarangException ex) {
                Logger.getLogger(NamaBarangView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(NamaBarangView.class.getName()).log(Level.SEVERE, null, ex);
        }        
        txtId.setText(String.valueOf(lastid));
        txtNamaBarang.requestFocus();
    }
}
