/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.masterdata.report.view;

/**
 *
 * @author Fauzi
 */
public class JIFReportTransaksi extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFReportTransaksi
     */
    public JIFReportTransaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportTransaksi1 = new Sinarelektronikapp.masterdata.report.view.ReportTransaksi();

        setClosable(true);
        setIconifiable(true);
        setTitle("Laporan Transaksi");
        setMinimumSize(new java.awt.Dimension(300, 33));
        getContentPane().add(reportTransaksi1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Sinarelektronikapp.masterdata.report.view.ReportTransaksi reportTransaksi1;
    // End of variables declaration//GEN-END:variables
}
