/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.masterData.report.view;

import Sinarelektronikapp.config.InternetProtocol;
import Sinarelektronikapp.masterData.report.core.Report;
import Sinarelektronikapp.masterData.report.core.ReportParam;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Fauzi
 */
public class PriceListReport extends javax.swing.JPanel {

    /**
     * Creates new form PriceListReport
     */
    public PriceListReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogMerekHA = new javax.swing.JDialog();
        cmbMerekHA = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        DialogMerekAL = new javax.swing.JDialog();
        cmbMErekAL = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        DialogMerekSP = new javax.swing.JDialog();
        cmbMerekSp = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btComplete = new javax.swing.JButton();
        btGrosirEceran = new javax.swing.JButton();
        btEceranOnly = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btKasirHa = new javax.swing.JButton();
        btGrosirEceran1 = new javax.swing.JButton();
        btEceranOnly1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btComplete2 = new javax.swing.JButton();
        btGrosirEceran2 = new javax.swing.JButton();
        btEceranOnly2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btComplete3 = new javax.swing.JButton();
        btGrosirEceran3 = new javax.swing.JButton();
        btEceranOnly3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btComplete4 = new javax.swing.JButton();
        btGrosirEceran4 = new javax.swing.JButton();
        btEceranOnly4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btEceranOnly6 = new javax.swing.JButton();

        DialogMerekHA.setTitle("Home Appliances");

        DialogMerekHA.getContentPane().add(cmbMerekHA, java.awt.BorderLayout.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/login.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        DialogMerekHA.getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        DialogMerekAL.setTitle("ALAT LISTRIK");

        cmbMErekAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMErekALActionPerformed(evt);
            }
        });
        DialogMerekAL.getContentPane().add(cmbMErekAL, java.awt.BorderLayout.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/login.png"))); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        DialogMerekAL.getContentPane().add(jButton2, java.awt.BorderLayout.PAGE_END);

        DialogMerekSP.setTitle("SPARE PARTS");

        DialogMerekSP.getContentPane().add(cmbMerekSp, java.awt.BorderLayout.CENTER);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/login.png"))); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        DialogMerekSP.getContentPane().add(jButton3, java.awt.BorderLayout.PAGE_END);

        setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Barang Kecil"));
        jPanel1.setLayout(new java.awt.GridLayout(5, 0));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tanpa Kategori"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        btComplete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/kasir.png"))); // NOI18N
        btComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompleteActionPerformed(evt);
            }
        });
        jPanel3.add(btComplete);

        btGrosirEceran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/grosir.png"))); // NOI18N
        btGrosirEceran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrosirEceranActionPerformed(evt);
            }
        });
        jPanel3.add(btGrosirEceran);

        btEceranOnly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/Eceran.png"))); // NOI18N
        btEceranOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEceranOnlyActionPerformed(evt);
            }
        });
        jPanel3.add(btEceranOnly);

        jPanel1.add(jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Home Appliances"));
        jPanel6.setLayout(new java.awt.GridLayout(1, 3));

        btKasirHa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/kasir.png"))); // NOI18N
        btKasirHa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKasirHaActionPerformed(evt);
            }
        });
        jPanel6.add(btKasirHa);

        btGrosirEceran1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/grosir.png"))); // NOI18N
        btGrosirEceran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrosirEceran1ActionPerformed(evt);
            }
        });
        jPanel6.add(btGrosirEceran1);

        btEceranOnly1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/Eceran.png"))); // NOI18N
        btEceranOnly1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEceranOnly1ActionPerformed(evt);
            }
        });
        jPanel6.add(btEceranOnly1);

        jPanel1.add(jPanel6);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Alat Listrik"));
        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        btComplete2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/kasir.png"))); // NOI18N
        btComplete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComplete2ActionPerformed(evt);
            }
        });
        jPanel4.add(btComplete2);

        btGrosirEceran2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/grosir.png"))); // NOI18N
        btGrosirEceran2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrosirEceran2ActionPerformed(evt);
            }
        });
        jPanel4.add(btGrosirEceran2);

        btEceranOnly2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/Eceran.png"))); // NOI18N
        btEceranOnly2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEceranOnly2ActionPerformed(evt);
            }
        });
        jPanel4.add(btEceranOnly2);

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Spare Parts"));
        jPanel5.setLayout(new java.awt.GridLayout(1, 3));

        btComplete3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/kasir.png"))); // NOI18N
        btComplete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComplete3ActionPerformed(evt);
            }
        });
        jPanel5.add(btComplete3);

        btGrosirEceran3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/grosir.png"))); // NOI18N
        btGrosirEceran3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrosirEceran3ActionPerformed(evt);
            }
        });
        jPanel5.add(btGrosirEceran3);

        btEceranOnly3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/Eceran.png"))); // NOI18N
        btEceranOnly3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEceranOnly3ActionPerformed(evt);
            }
        });
        jPanel5.add(btEceranOnly3);

        jPanel1.add(jPanel5);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Merek Tertentu"));
        jPanel7.setLayout(new java.awt.GridLayout(1, 3));

        btComplete4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/Home Appliances.png"))); // NOI18N
        btComplete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComplete4ActionPerformed(evt);
            }
        });
        jPanel7.add(btComplete4);

        btGrosirEceran4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/Alat Listrik.png"))); // NOI18N
        btGrosirEceran4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrosirEceran4ActionPerformed(evt);
            }
        });
        jPanel7.add(btGrosirEceran4);

        btEceranOnly4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/SpareParts.png"))); // NOI18N
        btEceranOnly4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEceranOnly4ActionPerformed(evt);
            }
        });
        jPanel7.add(btEceranOnly4);

        jPanel1.add(jPanel7);

        add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Barang Besar"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btEceranOnly6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/pricelistbb.png"))); // NOI18N
        btEceranOnly6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEceranOnly6ActionPerformed(evt);
            }
        });
        jPanel2.add(btEceranOnly6, java.awt.BorderLayout.CENTER);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void btCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompleteActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("kasirpricelist");
    }//GEN-LAST:event_btCompleteActionPerformed

    private void btGrosirEceranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrosirEceranActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("grosirpricelist");
    }//GEN-LAST:event_btGrosirEceranActionPerformed

    private void btEceranOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEceranOnlyActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("retailpricelist");
    }//GEN-LAST:event_btEceranOnlyActionPerformed

    private void btComplete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComplete2ActionPerformed
        // TODO add your handling code here:
            ReportParam rp=new ReportParam();
            rp.buildReportSingleParam("barangperkategori", "ALAT LISTRIK");        
    }//GEN-LAST:event_btComplete2ActionPerformed

    private void btGrosirEceran2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrosirEceran2ActionPerformed
        // TODO add your handling code here:
            ReportParam rp=new ReportParam();
            rp.buildReportSingleParam("baranggrosirperkategori", "ALAT LISTRIK");                        
    }//GEN-LAST:event_btGrosirEceran2ActionPerformed

    private void btEceranOnly2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEceranOnly2ActionPerformed
        // TODO add your handling code here:
            ReportParam rp=new ReportParam();
            rp.buildReportSingleParam("barangeceranperkategori", "ALAT LISTRIK");                                
    }//GEN-LAST:event_btEceranOnly2ActionPerformed

    private void btComplete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComplete3ActionPerformed
        // TODO add your handling code here:
            ReportParam rp=new ReportParam();
            rp.buildReportSingleParam("barangperkategori", "SPARE PARTS");        
    }//GEN-LAST:event_btComplete3ActionPerformed

    private void btGrosirEceran3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrosirEceran3ActionPerformed
        // TODO add your handling code here:
            ReportParam rp=new ReportParam();
            rp.buildReportSingleParam("baranggrosirperkategori", "SPARE PARTS");                        
    }//GEN-LAST:event_btGrosirEceran3ActionPerformed

    private void btEceranOnly3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEceranOnly3ActionPerformed
        // TODO add your handling code here:
            ReportParam rp=new ReportParam();
            rp.buildReportSingleParam("barangeceranperkategori", "SPARE PARTS");
    }//GEN-LAST:event_btEceranOnly3ActionPerformed

    private void btEceranOnly6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEceranOnly6ActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("barangbesar");        
    }//GEN-LAST:event_btEceranOnly6ActionPerformed

    private void btKasirHaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKasirHaActionPerformed
        // TODO add your handling code here:
            ReportParam rp=new ReportParam();
            rp.buildReportSingleParam("barangperkategori", "HOME APPLIANCES");
    }//GEN-LAST:event_btKasirHaActionPerformed

    private void btGrosirEceran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrosirEceran1ActionPerformed
        // TODO add your handling code here:
            ReportParam rp=new ReportParam();
            rp.buildReportSingleParam("baranggrosirperkategori", "HOME APPLIANCES");                
    }//GEN-LAST:event_btGrosirEceran1ActionPerformed

    private void btEceranOnly1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEceranOnly1ActionPerformed
        // TODO add your handling code here:
            ReportParam rp=new ReportParam();
            rp.buildReportSingleParam("barangeceranperkategori", "HOME APPLIANCES");                        
    }//GEN-LAST:event_btEceranOnly1ActionPerformed

    Connection conn = null;

    InternetProtocol ip = new InternetProtocol();    
    
    public void koneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://"+ip.getIpServer()+"/sinarelektronik?;", "root", "5430trisin9");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error koneksi pada barang view karena = "+ex);
        }
    }
    
    
    private void loadMerekHA(){
        koneksi();
        try{
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery("select distinct merek from barang where kategori='HOME APPLIANCES'");
            while (rs.next()) {                
                cmbMerekHA.addItem(rs.getString("merek"));
            }
        }catch(SQLException exception){
            JOptionPane.showMessageDialog(null, "Error dalam mendapatkan merek load merek HA karena "+exception);
        }
    }
    
    private void loadMerekAL(){
        koneksi();
        try{
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery("select distinct merek from barang where kategori='ALAT LISTRIK'");
            while (rs.next()) {                
                cmbMErekAL.addItem(rs.getString("merek"));
            }
        }catch(SQLException exception){
            JOptionPane.showMessageDialog(null, "Error dalam mendapatkan merek load merek AL karena "+exception);
        }
    }
    
    private void loadMerekSP(){
        koneksi();
        try{
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery("select distinct merek from barang where kategori='SPARE PARTS'");
            while (rs.next()) {                
                cmbMerekSp.addItem(rs.getString("merek"));
            }
        }catch(SQLException exception){
            JOptionPane.showMessageDialog(null, "Error dalam mendapatkan merek load merek SP karena "+exception);
        }
    }
    
    private void btComplete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComplete4ActionPerformed
        // TODO add your handling code here:        
        loadMerekHA();
        int y = 250;
        int x = 500;
        DialogMerekHA.setModal(true);
        DialogMerekHA.setLocation(x, y);
        DialogMerekHA.setSize(300, 120);
        DialogMerekHA.show();                        
    }//GEN-LAST:event_btComplete4ActionPerformed

    private void btGrosirEceran4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrosirEceran4ActionPerformed
        // TODO add your handling code here:
        loadMerekAL();
        int y = 250;
        int x = 500;
        DialogMerekAL.setModal(true);
        DialogMerekAL.setLocation(x, y);
        DialogMerekAL.setSize(300, 120);
        DialogMerekAL.show();                                
    }//GEN-LAST:event_btGrosirEceran4ActionPerformed

    private void btEceranOnly4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEceranOnly4ActionPerformed
        // TODO add your handling code here:
        loadMerekSP();
        int y = 250;
        int x = 500;
        DialogMerekSP.setModal(true);
        DialogMerekSP.setLocation(x, y);
        DialogMerekSP.setSize(300, 120);
        DialogMerekSP.show();                                
    }//GEN-LAST:event_btEceranOnly4ActionPerformed

    private void cmbMErekALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMErekALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMErekALActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ReportParam rp=new ReportParam();
        rp.buildReportDoubleParamPriceList("pricelistmerekha", "HOME APPLIANCES", cmbMerekHA.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ReportParam rp=new ReportParam();
        rp.buildReportDoubleParamPriceList("pricelistmerekal", "ALAT LISTRIK", cmbMErekAL.getSelectedItem().toString());        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ReportParam rp=new ReportParam();
        rp.buildReportDoubleParamPriceList("pricelistmereksp", "SPARE PARTS", cmbMerekSp.getSelectedItem().toString());
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogMerekAL;
    private javax.swing.JDialog DialogMerekHA;
    private javax.swing.JDialog DialogMerekSP;
    private javax.swing.JButton btComplete;
    private javax.swing.JButton btComplete2;
    private javax.swing.JButton btComplete3;
    private javax.swing.JButton btComplete4;
    private javax.swing.JButton btEceranOnly;
    private javax.swing.JButton btEceranOnly1;
    private javax.swing.JButton btEceranOnly2;
    private javax.swing.JButton btEceranOnly3;
    private javax.swing.JButton btEceranOnly4;
    private javax.swing.JButton btEceranOnly6;
    private javax.swing.JButton btGrosirEceran;
    private javax.swing.JButton btGrosirEceran1;
    private javax.swing.JButton btGrosirEceran2;
    private javax.swing.JButton btGrosirEceran3;
    private javax.swing.JButton btGrosirEceran4;
    private javax.swing.JButton btKasirHa;
    private javax.swing.JComboBox cmbMErekAL;
    private javax.swing.JComboBox cmbMerekHA;
    private javax.swing.JComboBox cmbMerekSp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
