/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.masterdata.report.view;

import Sinarelektronikapp.masterdata.report.core.Report;
import java.text.SimpleDateFormat;

/**
 *
 * @author Fauzi
 */
public class ReportMaster extends javax.swing.JPanel {

    /**
     * Creates new form ReportMaster
     */
    public ReportMaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMaster = new javax.swing.JPanel();
        btBarang = new javax.swing.JButton();
        btBarangBesar = new javax.swing.JButton();
        btBarangToko = new javax.swing.JButton();
        btMerek = new javax.swing.JButton();
        btPelangga = new javax.swing.JButton();
        btSatuan = new javax.swing.JButton();
        btSupplier = new javax.swing.JButton();
        btTipe = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelMaster.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Create LaporanData Master"));
        panelMaster.setMinimumSize(new java.awt.Dimension(1300, 131));
        panelMaster.setPreferredSize(new java.awt.Dimension(700, 150));
        panelMaster.setLayout(new java.awt.GridLayout(1, 7));

        btBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/barang.png"))); // NOI18N
        btBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBarangActionPerformed(evt);
            }
        });
        panelMaster.add(btBarang);

        btBarangBesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/barangbesar.png"))); // NOI18N
        btBarangBesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBarangBesarActionPerformed(evt);
            }
        });
        panelMaster.add(btBarangBesar);

        btBarangToko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/barangToko2.png"))); // NOI18N
        btBarangToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBarangTokoActionPerformed(evt);
            }
        });
        panelMaster.add(btBarangToko);

        btMerek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/merek.png"))); // NOI18N
        btMerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMerekActionPerformed(evt);
            }
        });
        panelMaster.add(btMerek);

        btPelangga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/pelanggan.png"))); // NOI18N
        btPelangga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPelanggaActionPerformed(evt);
            }
        });
        panelMaster.add(btPelangga);

        btSatuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/satuan.png"))); // NOI18N
        btSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSatuanActionPerformed(evt);
            }
        });
        panelMaster.add(btSatuan);

        btSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/supplier.png"))); // NOI18N
        btSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupplierActionPerformed(evt);
            }
        });
        panelMaster.add(btSupplier);

        btTipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/tipe.png"))); // NOI18N
        btTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTipeActionPerformed(evt);
            }
        });
        panelMaster.add(btTipe);

        add(panelMaster, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBarangActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("barangkecil");
    }//GEN-LAST:event_btBarangActionPerformed

    private void btMerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMerekActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("merek");              
    }//GEN-LAST:event_btMerekActionPerformed

    private void btPelanggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPelanggaActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("pelanggan");        
    }//GEN-LAST:event_btPelanggaActionPerformed

    private void btSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSatuanActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("satuan");        
    }//GEN-LAST:event_btSatuanActionPerformed

    private void btSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupplierActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("supplier");
    }//GEN-LAST:event_btSupplierActionPerformed

    private void btTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTipeActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("tipe");        
    }//GEN-LAST:event_btTipeActionPerformed

    private void btBarangBesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBarangBesarActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("barangbesar");                
    }//GEN-LAST:event_btBarangBesarActionPerformed

    private void btBarangTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBarangTokoActionPerformed
        // TODO add your handling code here:
        Report report=new Report();
        report.buildReport("barangtokomaster");
    }//GEN-LAST:event_btBarangTokoActionPerformed

    SimpleDateFormat formatTanggal=new SimpleDateFormat("yyyy-MM-dd");
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBarang;
    private javax.swing.JButton btBarangBesar;
    private javax.swing.JButton btBarangToko;
    private javax.swing.JButton btMerek;
    private javax.swing.JButton btPelangga;
    private javax.swing.JButton btSatuan;
    private javax.swing.JButton btSupplier;
    private javax.swing.JButton btTipe;
    private javax.swing.JPanel panelMaster;
    // End of variables declaration//GEN-END:variables
}
