/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.masterdata.report.view;

import Sinarelektronikapp.config.InternetProtocol;
import Sinarelektronikapp.masterdata.report.core.ReportParam;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fauzi
 */
public class ReportRetur extends javax.swing.JPanel {

    /**
     * Creates new form ReportRetur
     */
    public ReportRetur() {
        initComponents();
        koneksi();
        loadSupplier();
    }

    public Connection conn = null;
    InternetProtocol ip1 = new InternetProtocol();    
    public void koneksi(){
        String url = "jdbc:mysql://"+ip1.getIpServer()+"/sinarelektronik?;";
        String pass = "5430trisin9";
        String user = "root";
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReportRetur.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            conn = DriverManager.getConnection(url, user, pass);
        } catch (SQLException ex) {
            Logger.getLogger(ReportRetur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loadSupplier(){
        Statement s = null;
        try {
            s = conn.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(ReportRetur.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet rs = null;
        try {
            rs = s.executeQuery("select nama from supplier");
        } catch (SQLException ex) {
            Logger.getLogger(ReportRetur.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rs.next()){
                String supplier = null;
                try {
                    supplier = rs.getString("nama");
                } catch (SQLException ex) {
                    Logger.getLogger(ReportRetur.class.getName()).log(Level.SEVERE, null, ex);
                }
                cmbSupplier.addItem(supplier);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportRetur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panelTransaksi = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTanggalAwal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtTanggalAkhir = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btRetur = new javax.swing.JButton();
        btDetailRetur = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelTransaksi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Laporan Retur"));
        panelTransaksi.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Tanggal Awal :");
        jPanel1.add(jLabel1);
        jPanel1.add(txtTanggalAwal);

        jLabel2.setText("Tanggal Akhir :");
        jPanel1.add(jLabel2);
        jPanel1.add(txtTanggalAkhir);

        jLabel3.setText("Supplier :");
        jPanel1.add(jLabel3);

        jPanel1.add(cmbSupplier);

        jLabel4.setText("Status :");
        jPanel1.add(jLabel4);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "belum diproses", "sedang diproses" }));
        jPanel1.add(cmbStatus);

        panelTransaksi.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        btRetur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/returtombol.png"))); // NOI18N
        btRetur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReturActionPerformed(evt);
            }
        });
        jPanel2.add(btRetur);

        btDetailRetur.setText("Detail Retur");
        btDetailRetur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDetailReturActionPerformed(evt);
            }
        });
        jPanel2.add(btDetailRetur);

        panelTransaksi.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        add(panelTransaksi, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btReturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReturActionPerformed
        // TODO add your handling code here:
        if(txtTanggalAwal.getDate()==null){
            txtTanggalAwal.requestFocus();
            JOptionPane.showMessageDialog(null, "Tanggal Awal masih kosong");
            return;
        }else if (txtTanggalAkhir.getDate() == null){
            txtTanggalAkhir.requestFocus();
            JOptionPane.showMessageDialog(null, "Tanggal Akhir masih kosong");
            return;
        }
        else{
            ReportParam rp=new ReportParam();
            rp.buildReportDoubleParam("retur", txtTanggalAwal.getDate(), txtTanggalAkhir.getDate());
        }
    }//GEN-LAST:event_btReturActionPerformed

    private void btDetailReturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDetailReturActionPerformed
        // TODO add your handling code here:
        String supplier = cmbSupplier.getSelectedItem().toString();
        String status = cmbStatus.getSelectedItem().toString();
        if(txtTanggalAwal.getDate()==null){
            txtTanggalAwal.requestFocus();
            JOptionPane.showMessageDialog(null, "Tanggal Awal masih kosong");
            return;
        }else if (txtTanggalAkhir.getDate() == null){
            txtTanggalAkhir.requestFocus();
            JOptionPane.showMessageDialog(null, "Tanggal Akhir masih kosong");
            return;
        }
        else{
            JOptionPane.showMessageDialog(null, "tanggal1= "+txtTanggalAwal.getDate());
            JOptionPane.showMessageDialog(null, "tanggal2= "+txtTanggalAkhir.getDate());            
            JOptionPane.showMessageDialog(null, "supplier = "+supplier);
            JOptionPane.showMessageDialog(null, "status = "+status);
            ReportParam rp=new ReportParam();
            rp.buildReportQuadParam("retur", txtTanggalAwal.getDate(), txtTanggalAkhir.getDate(), supplier, status);
        }
    }//GEN-LAST:event_btDetailReturActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDetailRetur;
    private javax.swing.JButton btRetur;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JComboBox cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelTransaksi;
    private com.toedter.calendar.JDateChooser txtTanggalAkhir;
    private com.toedter.calendar.JDateChooser txtTanggalAwal;
    // End of variables declaration//GEN-END:variables
}
