/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.penjualan.barangbesar.view;

import Sinarelektronikapp.masterdata.barangbesar.controller.BarangController;
import Sinarelektronikapp.masterdata.barangbesar.database.barangDatabase;
import Sinarelektronikapp.masterdata.barangbesar.entity.barang;
import Sinarelektronikapp.masterdata.barangbesar.error.BarangException;
import Sinarelektronikapp.masterdata.barangbesar.model.BarangBesarModel;
import Sinarelektronikapp.masterdata.barangbesar.model.TabelModelBarangBesar;
import Sinarelektronikapp.masterdata.barangbesar.model.event.BarangBesarListener;
import Sinarelektronikapp.masterdata.barangbesar.service.BarangDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Fauzi
 */
public class ViewSearchBarangBesar2 extends javax.swing.JPanel implements BarangBesarListener {

    /**
     * Creates new form ViewSearchBarangBesar2
     */
    
    private TabelModelBarangBesar tabelmodelBarangBesar;
    
    private BarangController controller;                
    
    private BarangBesarModel model;
    
    public ViewSearchBarangBesar2() {
        
        tabelmodelBarangBesar = new TabelModelBarangBesar();
        
        model=  new BarangBesarModel();
        model.setListener(this);        
        
        controller = new BarangController();
        controller.setModel(model);
        
        initComponents();
        
        tabelBarang.setModel(tabelmodelBarangBesar);
        try {
            loadDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(ViewSearchBarangBesar2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BarangException ex) {
            Logger.getLogger(ViewSearchBarangBesar2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public JComboBox getCmbCari() {
        return cmbCari;
    }

    public void setCmbCari(JComboBox cmbCari) {
        this.cmbCari = cmbCari;
    }

    public JComboBox getCmbUrut() {
        return cmbUrut;
    }

    public void setCmbUrut(JComboBox cmbUrut) {
        this.cmbUrut = cmbUrut;
    }

    public JTextField getTxtKataKunci() {
        return txtKataKunci;
    }

    public void setTxtKataKunci(JTextField txtKataKunci) {
        this.txtKataKunci = txtKataKunci;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpTabel = new javax.swing.JPopupMenu();
        pilih = new javax.swing.JMenuItem();
        up = new javax.swing.JPanel();
        panelBackgroundUp = new Sinarelektronikapp.swinglib.panelGradUser();
        kiri = new javax.swing.JPanel();
        labeling4 = new Sinarelektronikapp.swinglib.labeling();
        labeling5 = new Sinarelektronikapp.swinglib.labeling();
        labeling6 = new Sinarelektronikapp.swinglib.labeling();
        kanan = new javax.swing.JPanel();
        atas = new javax.swing.JPanel();
        txtKataKunci = new javax.swing.JTextField();
        btCari = new javax.swing.JButton();
        tengah = new javax.swing.JPanel();
        cmbCari = new javax.swing.JComboBox();
        bawah = new javax.swing.JPanel();
        cmbUrut = new javax.swing.JComboBox();
        middle = new javax.swing.JPanel();
        panelGradUser3 = new Sinarelektronikapp.swinglib.panelGradUser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();

        pilih.setText("Pilih");
        pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihActionPerformed(evt);
            }
        });
        popUpTabel.add(pilih);

        setLayout(new java.awt.BorderLayout());

        up.setLayout(new java.awt.BorderLayout());

        panelBackgroundUp.setLayout(new java.awt.BorderLayout());

        kiri.setOpaque(false);
        kiri.setLayout(new java.awt.GridLayout(3, 1));

        labeling4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labeling4.setText("Masukkan kata kunci 2:");
        kiri.add(labeling4);

        labeling5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labeling5.setText("Cari data berdasarkan :");
        kiri.add(labeling5);

        labeling6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labeling6.setText("Urutkan data berdasarkan :");
        kiri.add(labeling6);

        panelBackgroundUp.add(kiri, java.awt.BorderLayout.WEST);

        kanan.setOpaque(false);
        kanan.setLayout(new java.awt.GridLayout(3, 0));

        atas.setOpaque(false);

        txtKataKunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKataKunciActionPerformed(evt);
            }
        });

        btCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageresource/cari.png"))); // NOI18N
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout atasLayout = new javax.swing.GroupLayout(atas);
        atas.setLayout(atasLayout);
        atasLayout.setHorizontalGroup(
            atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atasLayout.createSequentialGroup()
                .addComponent(txtKataKunci, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCari, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        atasLayout.setVerticalGroup(
            atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtKataKunci)
            .addComponent(btCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kanan.add(atas);

        tengah.setOpaque(false);
        tengah.setLayout(new java.awt.BorderLayout());

        cmbCari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id barangkecil", "id barcode", "nama barangkecil", "tipe", "merek", "harga", "satuan", "stok", "stok minimum", "supplier", "keterangan" }));
        cmbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCariActionPerformed(evt);
            }
        });
        tengah.add(cmbCari, java.awt.BorderLayout.CENTER);

        kanan.add(tengah);

        bawah.setOpaque(false);
        bawah.setLayout(new java.awt.BorderLayout());

        cmbUrut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id barangkecil", "id barcode", "nama barangkecil", "tipe", "merek", "harga", "satuan", "stok", "stok minimum", "supplier", "keterangan" }));
        cmbUrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUrutActionPerformed(evt);
            }
        });
        bawah.add(cmbUrut, java.awt.BorderLayout.CENTER);

        kanan.add(bawah);

        panelBackgroundUp.add(kanan, java.awt.BorderLayout.CENTER);

        up.add(panelBackgroundUp, java.awt.BorderLayout.CENTER);

        add(up, java.awt.BorderLayout.PAGE_START);

        middle.setLayout(new java.awt.BorderLayout());

        panelGradUser3.setLayout(new java.awt.BorderLayout());

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelBarangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelBarangMouseReleased(evt);
            }
        });
        tabelBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelBarangKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        panelGradUser3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        middle.add(panelGradUser3, java.awt.BorderLayout.CENTER);

        add(middle, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
       /* try {        
            // TODO add your handling code here:
            controller.cari(this, this);
        } catch (SQLException ex) {
            Logger.getLogger(ViewSearchBarangBesar2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (barangException ex) {
            Logger.getLogger(ViewSearchBarangBesar2.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.setSize(getWidth(), getHeight());*/

    }//GEN-LAST:event_btCariActionPerformed

    private void cmbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCariActionPerformed

    private void cmbUrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUrutActionPerformed
/*        try {
            controller.sort(this);
        } catch (SQLException ex) {
            Logger.getLogger(ViewSearchBarangBesar2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (barangException ex) {
            Logger.getLogger(ViewSearchBarangBesar2.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_cmbUrutActionPerformed

    private void txtKataKunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKataKunciActionPerformed
        // TODO add your handling code here:
        btCari.doClick();
    }//GEN-LAST:event_txtKataKunciActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "data dari tabel = "+tabelBarang.getValueAt(tabelBarang.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_tabelBarangMouseClicked
       
    
    private void tabelBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMousePressed
        // TODO add your handling code here:
        /*if(evt.isPopupTrigger()){
            popUpTabel.show(evt.getComponent(), evt.getX(), evt.getY());
        }*/
        JOptionPane.showMessageDialog(null, "data dari tabel = "+tabelBarang.getValueAt(tabelBarang.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_tabelBarangMousePressed

    private void tabelBarangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseReleased
        // TODO add your handling code here:
        /*if(evt.isPopupTrigger()){
            popUpTabel.show(evt.getComponent(), evt.getX(), evt.getY());
        }*/
        JOptionPane.showMessageDialog(null, "data dari tabel = "+tabelBarang.getValueAt(tabelBarang.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_tabelBarangMouseReleased

    private void pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihActionPerformed
        // TODO add your handling code here:
        if(tabelBarang.getSelectedRowCount()==1){
            String data=tabelBarang.getValueAt(tabelBarang.getSelectedRow(), 0).toString();
            txtKataKunci.setText(data);
        }
    }//GEN-LAST:event_pilihActionPerformed

    private void tabelBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelBarangKeyPressed
        // TODO add your handling code here:
        if(tabelBarang.getSelectedRowCount()==1){
            String data=tabelBarang.getValueAt(tabelBarang.getSelectedRow(), 0).toString();
            txtKataKunci.setText(data);
        }        
    }//GEN-LAST:event_tabelBarangKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.JButton btCari;
    private javax.swing.JComboBox cmbCari;
    private javax.swing.JComboBox cmbUrut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kanan;
    private javax.swing.JPanel kiri;
    private Sinarelektronikapp.swinglib.labeling labeling4;
    private Sinarelektronikapp.swinglib.labeling labeling5;
    private Sinarelektronikapp.swinglib.labeling labeling6;
    private javax.swing.JPanel middle;
    private Sinarelektronikapp.swinglib.panelGradUser panelBackgroundUp;
    private Sinarelektronikapp.swinglib.panelGradUser panelGradUser3;
    private javax.swing.JMenuItem pilih;
    private javax.swing.JPopupMenu popUpTabel;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JPanel tengah;
    private javax.swing.JTextField txtKataKunci;
    private javax.swing.JPanel up;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(BarangBesarModel model) {
        txtKataKunci.setText(model.getCari());
    }

    @Override
    public void onInsert(barang barang) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void onUpdate(barang barang) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void onDelete() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void onSearch(List list) {
        tabelmodelBarangBesar.setList(list);
    }

    @Override
    public void onSort(List list) {
        tabelmodelBarangBesar.setList(list);
    }
    
    public void loadDatabase() throws SQLException, BarangException{
        BarangDao dao = barangDatabase.getBarangDao();
        tabelmodelBarangBesar.setList(dao.selectAllBarang());
    }

}
