/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sinarelektronikapp.masterData.satuan.view;

import Sinarelektronikapp.config.UserLevel;
import Sinarelektronikapp.masterData.satuan.controller.satuanController;
import Sinarelektronikapp.masterData.satuan.database.satuanDatabase;
import Sinarelektronikapp.masterData.satuan.entity.satuan;
import Sinarelektronikapp.masterData.satuan.model.satuanModel;
import Sinarelektronikapp.masterData.satuan.model.tabelModelSatuan;
import Sinarelektronikapp.masterData.satuan.error.SatuanException;
import Sinarelektronikapp.masterData.satuan.model.event.satuanListener;
import Sinarelektronikapp.masterData.satuan.service.satuanDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fauzi
 */
public class SatuanView extends javax.swing.JPanel implements satuanListener, ListSelectionListener{

    /**
     * Creates new form tambahTipe
     */
    private tabelModelSatuan modelSatuan ;    
    
    private satuanModel model ;
    
    private satuanController controller ;
    
    public SatuanView() throws SQLException, SatuanException {
        modelSatuan = new tabelModelSatuan();

        model = new satuanModel();
        model.setListener(this);
        
        controller = new satuanController();
        controller.setModel(model);        
        
        initComponents();
        
        tabelSatuan.setModel(modelSatuan);
        tabelSatuan.getSelectionModel().addListSelectionListener(this);
        try {
            loadId();
        } catch (SatuanException ex) {
            Logger.getLogger(SatuanView.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadDatabase();      
        setLevel();
    }

    public JTable getTabelSatuan() {
        return tabelSatuan;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    
    public JTextField getTxtSatuan() {
        return txtSatuan;
    }

    public void setLevel(){
        UserLevel userLevel = new UserLevel();
        String levelAktif = userLevel.getUserLevelActive();
        switch(levelAktif){
            case "Pemilik Toko":
                    txtSatuan.setEnabled(true);
                    btTambah.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Administrator":
                    txtSatuan.setEnabled(true);
                    btTambah.setEnabled(true);
                    btDelete.setEnabled(true);
                    btReset.setEnabled(true);
                    btUpdate.setEnabled(true);
                break;
            case "Karyawan":
                    txtSatuan.setEnabled(false);
                    btTambah.setEnabled(false);
                    btDelete.setEnabled(false);
                    btReset.setEnabled(false);
                    btUpdate.setEnabled(false);                
                break;                        
            default:;
        }
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSatuan = new javax.swing.JTable();
        bawah = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        palingAtas = new javax.swing.JPanel();
        kiri = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kanan = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtSatuan = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        atas.setLayout(new java.awt.BorderLayout());

        tabelSatuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelSatuan);

        atas.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(atas, java.awt.BorderLayout.CENTER);

        bawah.setLayout(new java.awt.GridLayout(1, 4));

        btTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/tambah.png"))); // NOI18N
        btTambah.setMnemonic('T');
        btTambah.setFocusable(false);
        btTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        bawah.add(btTambah);

        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/update2.png"))); // NOI18N
        btUpdate.setMnemonic('U');
        btUpdate.setFocusable(false);
        btUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        bawah.add(btUpdate);

        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/hapus.png"))); // NOI18N
        btDelete.setMnemonic('H');
        btDelete.setFocusable(false);
        btDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        bawah.add(btDelete);

        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sinarelektronikapp/imageResource/reset.png"))); // NOI18N
        btReset.setMnemonic('R');
        btReset.setFocusable(false);
        btReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        bawah.add(btReset);

        add(bawah, java.awt.BorderLayout.PAGE_END);

        palingAtas.setLayout(new java.awt.BorderLayout());

        kiri.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("id :");
        kiri.add(jLabel2);

        jLabel1.setText("Satuan :");
        kiri.add(jLabel1);

        palingAtas.add(kiri, java.awt.BorderLayout.WEST);

        kanan.setLayout(new java.awt.GridLayout(2, 0));

        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFocusGained(evt);
            }
        });
        kanan.add(txtId);

        txtSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatuanActionPerformed(evt);
            }
        });
        kanan.add(txtSatuan);

        palingAtas.add(kanan, java.awt.BorderLayout.CENTER);

        add(palingAtas, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
            // TODO add your handling code here:
            controller.deletesatuan(this);
            controller.resetsatuan(this);
        try {
            loadId();
        } catch (SQLException ex) {
            Logger.getLogger(SatuanView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SatuanException ex) {
            Logger.getLogger(SatuanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
            // TODO add your handling code here:
            controller.updatesatuan(this);
        try {
            loadId();
        } catch (SQLException ex) {
            Logger.getLogger(SatuanView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SatuanException ex) {
            Logger.getLogger(SatuanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btUpdateActionPerformed

    public void tambah(){
        try {
            controller.insertsatuan(this);
            loadId();
        } catch (SQLException ex) {
            Logger.getLogger(SatuanView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SatuanException ex) {
            Logger.getLogger(SatuanView.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtSatuan.setText("");
        txtSatuan.requestFocus();
            
    }
    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
            // TODO add your handling code here:
            tambah();
    }//GEN-LAST:event_btTambahActionPerformed

    private void txtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusGained
        try {
            // TODO add your handling code here:
            loadId();
        } catch (SQLException ex) {
            Logger.getLogger(SatuanView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SatuanException ex) {
            Logger.getLogger(SatuanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtIdFocusGained

    private void txtSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatuanActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_txtSatuanActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        controller.resetsatuan(this);
    }//GEN-LAST:event_btResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atas;
    private javax.swing.JPanel bawah;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kanan;
    private javax.swing.JPanel kiri;
    private javax.swing.JPanel palingAtas;
    private javax.swing.JTable tabelSatuan;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtSatuan;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(satuanModel model) {
        txtId.setText(model.getIdsatuan());
        txtSatuan.setText(model.getNamasatuan());
    }

    @Override
    public void onInsert(satuan satuan) {
        modelSatuan.add(satuan);
    }

    @Override
    public void onUpdate(satuan satuan) {
        int index = tabelSatuan.getSelectedRow();
        modelSatuan.set(index, satuan);
    }

    @Override
    public void onDelete() {
        int index = tabelSatuan.getSelectedRow();
        modelSatuan.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try{
        satuan satuan = modelSatuan.get(tabelSatuan.getSelectedRow());
        
        txtId.setText(satuan.getIdsatuan());
        txtSatuan.setText(satuan.getNamasatuan());            
        }catch(IndexOutOfBoundsException exception){
            
        }
    }
    
    public void loadId() throws SQLException, SatuanException{
        satuanDao dao=satuanDatabase.getSatuanDao();        
        int id=dao.getLastId();        
        txtId.setText(String.valueOf(id));
        txtSatuan.requestFocus();
    }
    
    public void loadDatabase(){
        satuanDao dao = null;
        try {
             dao = satuanDatabase.getSatuanDao();
        } catch (SQLException ex) {
            Logger.getLogger(SatuanView.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            modelSatuan.setList(dao.selectAllSatuan());
        } catch (SatuanException ex) {
            Logger.getLogger(SatuanView.class.getName()).log(Level.SEVERE, null, ex);
        }
;
    }
}
