/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wissensalt.sinarelektronik.masterdata.report.view;

/**
 *
 * @author Fauzi
 */
public class JIFPriceListReport extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFPriceListReport
     */
    public JIFPriceListReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPriceListKeyword = new javax.swing.JDialog();
        priceListReport1 = new com.wissensalt.sinarelektronik.masterdata.report.view.PriceListReport();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setTitle("Price List Report");
        getContentPane().add(priceListReport1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialogPriceListKeyword;
    private com.wissensalt.sinarelektronik.masterdata.report.view.PriceListReport priceListReport1;
    // End of variables declaration//GEN-END:variables
}
