/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wissensalt.sinarelektronik.masterdata.report.view;

/**
 *
 * @author Fauzi
 */
public class JIFReportInventory extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFReportInventory
     */
    public JIFReportInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportInventory1 = new com.wissensalt.sinarelektronik.masterdata.report.view.ReportInventory();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Report InventoryBarangKecilDTO");
        getContentPane().add(reportInventory1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.wissensalt.sinarelektronik.masterdata.report.view.ReportInventory reportInventory1;
    // End of variables declaration//GEN-END:variables
}
